language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - 'nightly'

matrix:
  allow_failures:
    - php: 'nightly'

before_script:
  - composer install --no-interaction

script:
  - composer check-style
  - composer analyze
  - composer test
  - composer check-tests

after_script:
  - vendor/bin/php-coveralls
